//
//  Object.hpp
//  SQLite3 Data Access Layer
//
//  Created by Julian Koksal on 2023-02-12.
//

#ifndef Object_h
#define Object_h

#include <any>
#include <map>
#include <set>
#include <string>

namespace DB
{

class Object
{
    friend class Handle;
private:
    virtual const std::string& table() const = 0;
    
    virtual const std::vector<std::string>& columns() const = 0;
    
    virtual const std::set<std::string>& keys() const = 0;
    
    virtual bool isAutoGeneratedKey() const = 0;
    
    virtual std::map<std::string, std::any> toMap() const = 0;
    
    virtual Object* fromMap(const std::map<std::string, std::any>& dbObjectMap) const = 0;
};

}

#endif /* Object_h */
