//
//  MenuItem.hpp
//  SQLite3 Data Access Layer
//
//  Created by Julian Koksal on 2023-02-13.
//

#ifndef MenuItem_hpp
#define MenuItem_hpp

#include <any>
#include <map>
#include <set>
#include <string>
#include <vector>

#include "DB/Object.hpp"

class MenuItem : public DB::Object
{
public:
    MenuItem(const std::string& name = "", const double price = 0.00);
    
    std::string name() const;
    
    double price() const;
    
    void name(const std::string& value);
    
    void price(const double value);
    
private:
    std::string name_;
    
    double price_;
    
    virtual const std::string& table() const override;
    
    virtual const std::vector<std::string>& columns() const override;
    
    virtual const std::set<std::string>& keys() const override;
    
    virtual bool isAutoGeneratedKey() const override;
    
    virtual std::map<std::string, std::any> toMap() const override;
    
    virtual DB::Object* fromMap(const std::map<std::string, std::any>& dbObjectMap) const override;
};

#endif /* MenuItem_hpp */
